### ISSUE TITLE
unable to produce .br or .gz files for assets which reside in nested folders

### ISSUE THREAD

**Issue by IsaacHub** [ralscha/parcel-plugin-compress#10]
I'm using this plugin along with [https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure) to re-order the directory structure, and the issue is, `dist-structure` plugin moved `.js` and `.css` files to `dist/js` and `dist/css` folders before `parcel-plugin-compress` executes.

This plugin is just looking for files in `dist/` folder only.

Can you fix this by improving this plugin to look for files in all nested directories? so that this issue can easily be fixed.

**Comment by ralscha** [comment]
Not sure how to fix that because the `parcel-plugin-compress` receives the files it has to compress from Parcel. 

A workaround for now is to use another tool to compress the files. 
```
npm install bread-compressor-cli -D
```
package.json
```json
"scripts": {
    "build": "parcel build src/index.html --public-url ./",
    "postbuild": "bread-compressor dist"
  },
```

**Comment by IsaacHub** [comment]
I modified the `index.js` file to get all the files inside those nested directories, like following:
and **it worked perfectly:**

I put these inside the `try` block of `bundler.on('bundled', async (bundle)`
```
const { config: { gzip, brotli, threshold,extensions,distName } } = (await explorer.search()) || { config: defaultOptions };

const getAllFiles = (dir, files, result, regex) => {
    files = files || fs.readdirSync(dir);
    result = result || [];
    regex = regex || new RegExp(`\\${extensions}$`)
    for (let i = 0; i < files.length; i++) {
        let file = path.join(dir, files[i]);
        if (fs.statSync(file).isDirectory()) {
            try {
                result = getAllFiles(file, fs.readdirSync(file), result, regex);
            } catch (error) {
                continue;
            }
        } else {
            if (regex.test(file)) {
                file = file.replace(/\\\\/g, "\\");
                result.push(file);
            }
        }
    }
    return result;
}

const bundledFiles = getAllFiles(path.resolve(distName));
```

and removed existing `function* filesToCompress` and replaced it by

```
[...bundledFiles].forEach(file => {
    queue.add(() => gzipCompress(file, {...defaultOptions.gzip, threshold, ...gzip
    }));
    queue.add(() => brotliCompress(file, {...defaultOptions.brotli, threshold, ...brotli
    }));
});
```
I removed `test` property and replaced by `extensions` and `distName` and now my `.compressrc` looks like:

```
{
.......
"extensions": ".js|.css|.html|.png|.jpg|.jpeg|.gif|.svg",
"distName":"./dist"
.......
}
```
**HAPPY ENDING...!**
