### ISSUE TITLE
Could be possible to only compress when building?

### ISSUE THREAD

**Issue by dortamiguel** [ralscha/parcel-plugin-compress#2]
It looks like when I'm on dev mode still compresses al the files

![image](https://user-images.githubusercontent.com/3449006/42726591-ccee4f2c-878e-11e8-8d82-650cd111212a.png)

**Comment by ralscha** [comment]
The plugin does not compress anything in dev mode. The problem is that the plugin always prints the log "Compressing bundled files..." even it does nothing. 

I released a new version 1.0.5 where I moved this log statement. The plugin now only prints it when it starts compressing files.

**Comment by dortamiguel** [comment]
Thank you 🙂
