### ISSUE TITLE
Requires Python

### ISSUE THREAD

**Issue by thiagodp** [ralscha/parcel-plugin-compress#9]
Package `node-zopfli-es` requires Python.

Checked on Windows 10, Node 8.11.3, Node-Gyp 5.0.2

**Comment by ralscha** [comment]
`node-zopfli-es` and `iltorb` are optional dependencies.     
http://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html

```
  "optionalDependencies": {
    "iltorb": "2.4.4",
    "node-zopfli-es": "1.0.3"
  }
```

If the installation fails the plugin should still work thanks to [`@gfx/zopfli`](https://github.com/gfx/universal-zopfli-js#readme) and [`brotli`](https://github.com/foliojs/brotli.js). Both are implemented with WebAssembly.

**Comment by damianobarbati** [comment]
How can we remove this annoying warning? 
```
.Compression warning: node-zopfli-es could not be loaded. Falling back to @gfx/zopfli.
```
